---
# device-matching regular expressions
# to use these in shell commands, 
# use a SINGLE QUOTE around them or else they will not work

# # this matches a full block device partition pathname
# # if you want it to accept nothing past the partition name, 
# # you have to append something to the regex, like a $ sign
ceph_osd_partition_regex: "/dev/([hsv]d[a-z]{1,2}|xvd[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p|fio[a-z]{1,2})[0-9]{1,2}"

# # this matches just the block device, not a partition
# # if you want it to accept only device names and not partitions, you 
# # have to append something to the regex, like a $ sign
ceph_osd_blkdev_regex: "/dev/([hsv]d[a-z]{1,2}|xvd[a-z]{1,2}|cciss/c[0-9]d[0-9]|nvme[0-9]n[0-9]|fio[a-z]{1,2})"

# # this extracts just the partition number using egrep -o
ceph_osd_partnum_regex: "[0-9]{1,2}$"

